### ISSUE TITLE
Please block pedo sites from .Gq

### ISSUE THREAD

**Issue by Deathscry** [starius/onion2web#11]
Block pedo sites from onion.Gq

**Comment by la8** [comment]
That's the shame such sites exist. Send them to me privately. We will do our best to block them.

**Comment by Deathscry** [comment]
How do i pm the links to you?

**Comment by la8** [comment]
Send them to la82@protonmail.ch please.

**Comment by la8** [comment]
the service will be switched to using the black list maintained by ahmia.fi
You can submit the sites to https://ahmia.fi/blacklist/
